<?php

namespace App\Console\Commands;

use App\Models\Product;
use Illuminate\Console\Command;

class fill extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:fill';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $data=
            [
              [
                  'title'=>'Minifigure, Utensil Candle',
                  'color_id'=>'1',
                  'number'=>'6234807',
                  'bricklink_number'=>'37762',
                  'price'=>'12',
                  'is_available'=>'1',
                  'category_id'=>'1',
                  'weight'=>'0.28',
                  'amount'=>3
              ],
                [
                    'title'=>'Tile 1 x 1',
                    'color_id'=>'1',
                    'number'=>'307001',
                    'bricklink_number'=>'3070',
                    'other_numbers'=>'3070b, 30039, 35403, 39727, 53836',
                    'price'=>'9',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.16',
                    'amount'=>2
                ],
                [
                    'title'=>'Minifigure, Plume Feather Triple Compact / Flame / Water with Small Pin',
                    'color_id'=>'1',
                    'number'=>'6097694',
                    'bricklink_number'=>'64647',
                    'other_numbers'=>'28661',
                    'price'=>'15',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.19',
                    'amount'=>1
                ],
                [
                    'title'=>'Slope 30 1 x 2 x 2/3',
                    'color_id'=>'1',
                    'number'=>'4547489',
                    'bricklink_number'=>'85984',
                    'other_numbers'=>'83473',
                    'price'=>'8',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.35',
                    'amount'=>2
                ],
                [
                    'title'=>'Tile, Round 2 x 2 with Open Stud',
                    'color_id'=>'1',
                    'number'=>'6093053',
                    'bricklink_number'=>'18674',
                    'other_numbers'=>'',
                    'price'=>'6',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.35',
                    'amount'=>1
                ],
                [
                    'title'=>'Plate 1 x 2',
                    'color_id'=>'1',
                    'number'=>'302301',
                    'bricklink_number'=>'3023',
                    'other_numbers'=>'6225, 28653',
                    'price'=>'3.5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.36',
                    'amount'=>6
                ],
                [
                    'title'=>'Plate 2 x 2 Corner',
                    'color_id'=>'1',
                    'number'=>'242001',
                    'bricklink_number'=>'2420',
                    'other_numbers'=>'63325',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.54',
                    'amount'=>4
                ],
                [
                    'title'=>'Owl, Angular Features with Black Beak, Yellow Eyes, and Light Bluish Gray Rippled Chest Feathers Pattern (HP Hedwig)',
                    'color_id'=>'1',
                    'number'=>'6236694',
                    'bricklink_number'=>'92084pb03',
                    'other_numbers'=>'',
                    'price'=>'120',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.5',
                    'amount'=>1
                ],
                [
                    'title'=>'Tile 1 x 6',
                    'color_id'=>'1',
                    'number'=>'663601',
                    'bricklink_number'=>'6636',
                    'other_numbers'=>'63324, 75702',
                    'price'=>'13',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.83',
                    'amount'=>2
                ],
                [
                    'title'=>'Wedge 6 x 4 x 2/3 Quad Curved',
                    'color_id'=>'1',
                    'number'=>'4646574',
                    'bricklink_number'=>'98281',
                    'other_numbers'=>'',
                    'price'=>'15',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'3.7',
                    'amount'=>1
                ],
                #tan
                [
                    'title'=>'Support 1 x 1 x 6 Solid Pillar',
                    'color_id'=>'2',
                    'number'=>'6178916',
                    'bricklink_number'=>'43888',
                    'other_numbers'=>'',
                    'price'=>'25',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'2',
                    'amount'=>2
                ],
                [
                    'title'=>'Technic, Gear 12 Tooth Bevel',
                    'color_id'=>'2',
                    'number'=>'4565452',
                    'bricklink_number'=>'6589',
                    'other_numbers'=>'',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.29',
                    'amount'=>2
                ],
                [
                    'title'=>'Plate, Round 1 x 2 with Open Studs',
                    'color_id'=>'2',
                    'number'=>'6212758',
                    'bricklink_number'=>'35480',
                    'other_numbers'=>'',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.27',
                    'amount'=>4
                ],
                [
                    'title'=>'Tile 1 x 2 with Reddish Brown \'Wingardium Leviosa\' and Wand and White Feather Pattern',
                    'color_id'=>'2',
                    'number'=>'6236728',
                    'bricklink_number'=>'3069pb0649',
                    'other_numbers'=>'3069bpb0649',
                    'price'=>'30',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.26',
                    'amount'=>1
                ],
                [
                    'title'=>'Tile 2 x 2 with Groove with Newspaper, \'the Daily Prophet\', \'EXCLUSIVE HARRY POTTER\', \'The Boy who LIVED!\', and Image of Boy with Glasses Pattern',
                    'color_id'=>'2',
                    'number'=>'6236629',
                    'bricklink_number'=>'3068bpb1156',
                    'other_numbers'=>'',
                    'price'=>'45',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.48',
                    'amount'=>1
                ],
                [
                    'title'=>'Cylinder Half 2 x 4 x 2 with 1 x 2 Cutout',
                    'color_id'=>'2',
                    'number'=>'6234107',
                    'bricklink_number'=>'24593',
                    'other_numbers'=>'35402',
                    'price'=>'26',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'2.3',
                    'amount'=>1
                ],
                #red
                [
                    'title'=>'Technic, Axle 2L Notched',
                    'color_id'=>'5',
                    'number'=>'4142865',
                    'bricklink_number'=>'32062',
                    'other_numbers'=>'',
                    'price'=>'3',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.26',
                    'amount'=>4
                ],
                [
                    'title'=>'Technic, Axle Connector 2L (Smooth with x Hole + Orientation)',
                    'color_id'=>'5',
                    'number'=>'4513174',
                    'bricklink_number'=>'6538c',
                    'other_numbers'=>'59443',
                    'price'=>'4',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.4',
                    'amount'=>1
                ],
                [
                    'title'=>'Tile 2 x 3',
                    'color_id'=>'5',
                    'number'=>'6189130',
                    'bricklink_number'=>'26603',
                    'other_numbers'=>'',
                    'price'=>'17',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.68',
                    'amount'=>2
                ],
                #blue
                [
                    'title'=>'Technic, Axle 1L with Pin with Friction Ridges',
                    'color_id'=>'7',
                    'number'=>'4206482',
                    'bricklink_number'=>'43093',
                    'other_numbers'=>'',
                    'price'=>'3',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.26',
                    'amount'=>4
                ],
                #black
                [
                    'title'=>'Technic, Pin with Friction Ridges and Pin Hole',
                    'color_id'=>'11',
                    'number'=>'6073231',
                    'bricklink_number'=>'15100',
                    'other_numbers'=>'65487',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.4',
                    'amount'=>4
                ],
                [
                    'title'=>'Plate 1 x 1',
                    'color_id'=>'11',
                    'number'=>'302426',
                    'bricklink_number'=>'3024',
                    'other_numbers'=>'28554, 30008, 63326',
                    'price'=>'8',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.2',
                    'amount'=>2
                ],
                [
                    'title'=>'Minifigure, Utensil Wand, 2 on Sprue',
                    'color_id'=>'11',
                    'number'=>'6232209',
                    'bricklink_number'=>'36752',
                    'other_numbers'=>'',
                    'price'=>'25',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.24',
                    'amount'=>1
                ],
                [
                    'title'=>'Brick, Round 2 x 2 with Axle Hole and Grille / Fluted Profile',
                    'color_id'=>'11',
                    'number'=>'6024730',
                    'bricklink_number'=>'92947',
                    'other_numbers'=>'',
                    'price'=>'8',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.98',
                    'amount'=>1
                ],
                [
                    'title'=>'Tile 1 x 2',
                    'color_id'=>'11',
                    'number'=>'306926',
                    'bricklink_number'=>'3069',
                    'other_numbers'=>'3069b, 30070, 35386, 37293, 54285, 88630',
                    'price'=>'6',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.26',
                    'amount'=>3
                ],
                [
                    'title'=>'Tire 17.5mm D. x 6mm with Shallow Staggered Treads - Band Around Center of Tread',
                    'color_id'=>'11',
                    'number'=>'4617848',
                    'bricklink_number'=>'92409',
                    'other_numbers'=>'',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.78',
                    'amount'=>4
                ],
                [
                    'title'=>'Bracket 1 x 2 - 2 x 2 Inverted',
                    'color_id'=>'11',
                    'number'=>'6000650',
                    'bricklink_number'=>'99207',
                    'other_numbers'=>'',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.8',
                    'amount'=>1
                ],
                [
                    'title'=>'Minifigure, Utensil Seat / Chair 2 x 2',
                    'color_id'=>'11',
                    'number'=>'407926',
                    'bricklink_number'=>'4079',
                    'other_numbers'=>'4079b',
                    'price'=>'15',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.8',
                    'amount'=>1
                ],
                [
                    'title'=>'Minifigure, Utensil Tool Mallet / Hammer',
                    'color_id'=>'11',
                    'number'=>'452226',
                    'bricklink_number'=>'4522',
                    'other_numbers'=>'',
                    'price'=>'6',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.13',
                    'amount'=>1
                ],
                [
                    'title'=>'Minifigure, Utensil Axe',
                    'color_id'=>'11',
                    'number'=>'383526',
                    'bricklink_number'=>'3835',
                    'other_numbers'=>'',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.24',
                    'amount'=>1
                ],
                [
                    'title'=>'Technic, Axle 4L',
                    'color_id'=>'11',
                    'number'=>'370526',
                    'bricklink_number'=>'3705',
                    'other_numbers'=>'',
                    'price'=>'2.8',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.59',
                    'amount'=>1
                ],
                [
                    'title'=>'Slope, Curved 4 x 1 x 2/3 Double',
                    'color_id'=>'11',
                    'number'=>'4613153',
                    'bricklink_number'=>'93273',
                    'other_numbers'=>'',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.6',
                    'amount'=>1
                ],
                [
                    'title'=>'Plate, Modified 1 x 4 with Wheels Holder',
                    'color_id'=>'11',
                    'number'=>'292626',
                    'bricklink_number'=>'2926',
                    'other_numbers'=>'42946',
                    'price'=>'4',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.9',
                    'amount'=>2
                ],
                [
                    'title'=>'Tile, Modified 3 x 4 with 4 Studs in Center',
                    'color_id'=>'11',
                    'number'=>'6076678',
                    'bricklink_number'=>'88646',
                    'other_numbers'=>'17836',
                    'price'=>'30',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.52',
                    'amount'=>1
                ],
                [
                    'title'=>'Technic, Gearbox 4 x 4 x 1 2/3',
                    'color_id'=>'11',
                    'number'=>'6169982',
                    'bricklink_number'=>'6585',
                    'other_numbers'=>'28830',
                    'price'=>'12',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'4.5',
                    'amount'=>1
                ],
                [
                    'title'=>'Vehicle, Base 4 x 10 x 2/3 with 4 x 2 Recessed Center with Smooth Underside',
                    'color_id'=>'11',
                    'number'=>'4656764',
                    'bricklink_number'=>'30029',
                    'other_numbers'=>'',
                    'price'=>'15',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'6',
                    'amount'=>1
                ],
                [
                    'title'=>'Plate 1 x 12',
                    'color_id'=>'11',
                    'number'=>'4514845',
                    'bricklink_number'=>'60479',
                    'other_numbers'=>'',
                    'price'=>'20',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.95',
                    'amount'=>1
                ],
                #green
                [
                    'title'=>'Plate, Round 1 x 1 with Flower Edge (5 Petals)',
                    'color_id'=>'6',
                    'number'=>'6135287',
                    'bricklink_number'=>'24866',
                    'other_numbers'=>'',
                    'price'=>'8',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.09',
                    'amount'=>4
                ],
                [
                    'title'=>'Plant Flower Stem with Bar Holder, Bar, and 3 Stems',
                    'color_id'=>'6',
                    'number'=>'6135278',
                    'bricklink_number'=>'24855',
                    'other_numbers'=>'',
                    'price'=>'8',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.16',
                    'amount'=>5
                ],
                #trans-clear
                [
                    'title'=>'Brick, Round 1 x 1',
                    'color_id'=>'12',
                    'number'=>'6223655',
                    'bricklink_number'=>'3062',
                    'other_numbers'=>'3062b, 18860, 30068, 35390',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.28',
                    'amount'=>2
                ],
                [
                    'title'=>'Plate, Round 1 x 1',
                    'color_id'=>'12',
                    'number'=>'6240030',
                    'bricklink_number'=>'4073',
                    'other_numbers'=>'6141, 15570, 30057, 34823, 39799, 44325, 51809',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.12',
                    'amount'=>1
                ],
                [
                    'title'=>'Tile, Round 1 x 1 with Bar and Pin Holder',
                    'color_id'=>'12',
                    'number'=>'6186867',
                    'bricklink_number'=>'20482',
                    'other_numbers'=>'31561, 31570, 100765',
                    'price'=>'4',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.16',
                    'amount'=>1
                ],
                [
                    'title'=>'Windscreen 2 x 4 x 2 Vertical',
                    'color_id'=>'12',
                    'number'=>'6240532',
                    'bricklink_number'=>'4594',
                    'other_numbers'=>'35160',
                    'price'=>'18',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'3.06',
                    'amount'=>1
                ],
                #trans-red
                [
                    'title'=>'Brick, Round 1 x 1',
                    'color_id'=>'17',
                    'number'=>'6238673',
                    'bricklink_number'=>'3062',
                    'other_numbers'=>'3062b, 18860, 30068, 35390',
                    'price'=>'6',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.28',
                    'amount'=>3
                ],
                [
                    'title'=>'Rock 1 x 1 Jewel 24 Facet',
                    'color_id'=>'17',
                    'number'=>'6247785',
                    'bricklink_number'=>'30153',
                    'other_numbers'=>'28556',
                    'price'=>'4',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.22',
                    'amount'=>1
                ],
                #trans-dark blue
                [
                    'title'=>'Brick, Round 1 x 1',
                    'color_id'=>'14',
                    'number'=>'6238044',
                    'bricklink_number'=>'3062',
                    'other_numbers'=>'3062b, 18860, 30068, 35390',
                    'price'=>'6',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.28',
                    'amount'=>3
                ],
                #trans-yellow
                [
                    'title'=>'Brick, Round 1 x 1',
                    'color_id'=>'19',
                    'number'=>'6238674',
                    'bricklink_number'=>'3062',
                    'other_numbers'=>'3062b, 18860, 30068, 35390',
                    'price'=>'9',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.28',
                    'amount'=>1
                ],
                [
                    'title'=>'Plate, Round 1 x 1',
                    'color_id'=>'19',
                    'number'=>'6240216',
                    'bricklink_number'=>'4073',
                    'other_numbers'=>'6141, 15570, 30057, 34823, 39799, 44325, 51809',
                    'price'=>'2.5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.12',
                    'amount'=>2
                ],
                [
                    'title'=>'Slope 30 1 x 1 x 2/3',
                    'color_id'=>'19',
                    'number'=>'6245265',
                    'bricklink_number'=>'54200',
                    'other_numbers'=>'18862, 33847, 35338, 50746, 63290',
                    'price'=>'2.8',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.21',
                    'amount'=>2
                ],
                #trans-green
                [
                    'title'=>'Brick, Round 1 x 1',
                    'color_id'=>'20',
                    'number'=>'6238046',
                    'bricklink_number'=>'3062',
                    'other_numbers'=>'3062b, 18860, 30068, 35390',
                    'price'=>'6',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.28',
                    'amount'=>2
                ],
                #Medium blue
                [
                    'title'=>'Brick, Modified 1 x 1 with Headlight',
                    'color_id'=>'42',
                    'number'=>'6070689',
                    'bricklink_number'=>'4070',
                    'other_numbers'=>'4070a, 30069, 35388',
                    'price'=>'15.5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.36',
                    'amount'=>2
                ],
                [
                    'title'=>'Plate 1 x 1',
                    'color_id'=>'42',
                    'number'=>'4179826',
                    'bricklink_number'=>'3024',
                    'other_numbers'=>'28554, 30008, 63326',
                    'price'=>'6',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.2',
                    'amount'=>6
                ],
                [
                    'title'=>'Slope 30 1 x 1 x 2/3',
                    'color_id'=>'42',
                    'number'=>'4565363',
                    'bricklink_number'=>'54200',
                    'other_numbers'=>'18862, 33847, 35338, 50746, 63290',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.21',
                    'amount'=>4
                ],
                [
                    'title'=>'Brick 1 x 1',
                    'color_id'=>'42',
                    'number'=>'4179830',
                    'bricklink_number'=>'3005',
                    'other_numbers'=>'30071, 35382, 3005f1, 3005f2, 3005f3',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.44',
                    'amount'=>2
                ],
                [
                    'title'=>'Bracket 1 x 1 - 1 x 1',
                    'color_id'=>'42',
                    'number'=>'6236112',
                    'bricklink_number'=>'36841',
                    'other_numbers'=>'',
                    'price'=>'11',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.28',
                    'amount'=>4
                ],
                [
                    'title'=>'Slope, Inverted 45 2 x 1',
                    'color_id'=>'42',
                    'number'=>'4598015',
                    'bricklink_number'=>'3665',
                    'other_numbers'=>'',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.66',
                    'amount'=>6
                ],
                [
                    'title'=>'Slope 45 2 x 1',
                    'color_id'=>'42',
                    'number'=>'4626883',
                    'bricklink_number'=>'3040',
                    'other_numbers'=>'6270, 35281',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.69',
                    'amount'=>2
                ],
                [
                    'title'=>'Door 1 x 3 x 2 Right - Open Between Top and Bottom Hinge with Horizontal White Stripe Pattern',
                    'color_id'=>'42',
                    'number'=>'6236639',
                    'bricklink_number'=>'92263pb004',
                    'other_numbers'=>'',
                    'price'=>'14',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.94',
                    'amount'=>1
                ],
                [
                    'title'=>'Plate, Modified 1 x 2 with Bar Handle on Side - Free Ends',
                    'color_id'=>'42',
                    'number'=>'6195159',
                    'bricklink_number'=>'2540',
                    'other_numbers'=>'',
                    'price'=>'14',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.63',
                    'amount'=>2
                ],
                [
                    'title'=>'Tile 2 x 2 Corner',
                    'color_id'=>'42',
                    'number'=>'6167572',
                    'bricklink_number'=>'14719',
                    'other_numbers'=>'',
                    'price'=>'7',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.43',
                    'amount'=>2
                ],
                [
                    'title'=>'Door 1 x 3 x 2 Left - Open Between Top and Bottom Hinge with Horizontal White Stripe Pattern',
                    'color_id'=>'42',
                    'number'=>'6236642',
                    'bricklink_number'=>'92262pb004',
                    'other_numbers'=>'',
                    'price'=>'14',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.94',
                    'amount'=>1
                ],
                [
                    'title'=>'Tile 1 x 4',
                    'color_id'=>'42',
                    'number'=>'4597999',
                    'bricklink_number'=>'2431',
                    'other_numbers'=>'35371, 75703, 91143, 100687',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.54',
                    'amount'=>7
                ],
                [
                    'title'=>'Plate 1 x 4',
                    'color_id'=>'42',
                    'number'=>'4179828',
                    'bricklink_number'=>'3710',
                    'other_numbers'=>'',
                    'price'=>'5.3',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.71',
                    'amount'=>6
                ],
                [
                    'title'=>'Slope, Curved 2 x 4 x 1 1/3 with 4 Recessed Studs',
                    'color_id'=>'42',
                    'number'=>'6149564',
                    'bricklink_number'=>'6081',
                    'other_numbers'=>'',
                    'price'=>'22',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'2.78',
                    'amount'=>1
                ],
                [
                    'title'=>'Wedge 4 x 4 x 2/3 Triple Curved',
                    'color_id'=>'42',
                    'number'=>'6234542',
                    'bricklink_number'=>'45677',
                    'other_numbers'=>'',
                    'price'=>'32',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'2.67',
                    'amount'=>1
                ],
                [
                    'title'=>'Plate 1 x 6',
                    'color_id'=>'42',
                    'number'=>'4179829',
                    'bricklink_number'=>'3666',
                    'other_numbers'=>'',
                    'price'=>'12',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.06',
                    'amount'=>5
                ],
                [
                    'title'=>'Plate 2 x 6',
                    'color_id'=>'42',
                    'number'=>'6101858',
                    'bricklink_number'=>'3795',
                    'other_numbers'=>'',
                    'price'=>'10.5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.74',
                    'amount'=>3
                ],
                #trans-black
                [
                    'title'=>'Cone 1 x 1 with Top Groove',
                    'color_id'=>'13',
                    'number'=>'4567339',
                    'bricklink_number'=>'4589b',
                    'other_numbers'=>'28701, 59900, 64288',
                    'price'=>'9',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.25',
                    'amount'=>1
                ],
                #dark tan
                [
                    'title'=>'Minifigure, Utensil Wand, 2 on Sprue',
                    'color_id'=>'69',
                    'number'=>'6235074',
                    'bricklink_number'=>'36752',
                    'other_numbers'=>'',
                    'price'=>'25',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.24',
                    'amount'=>1
                ],
                [
                    'title'=>'Tile, Round 2 x 2 with Hole',
                    'color_id'=>'69',
                    'number'=>'6132790',
                    'bricklink_number'=>'15535',
                    'other_numbers'=>'',
                    'price'=>'9',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.32',
                    'amount'=>1
                ],
                [
                    'title'=>'Slope, Curved 2 x 2 x 2/3',
                    'color_id'=>'69',
                    'number'=>'6093038',
                    'bricklink_number'=>'15068',
                    'other_numbers'=>'78565',
                    'price'=>'8',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.57',
                    'amount'=>2
                ],
                #Dark Green
                [
                    'title'=>'Slope 30 1 x 1 x 2/3',
                    'color_id'=>'80',
                    'number'=>'4504375',
                    'bricklink_number'=>'54200',
                    'other_numbers'=>'18862, 33847, 35338, 50746, 63290',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.21',
                    'amount'=>11
                ],
                [
                    'title'=>'Plate, Round 2 x 2 with Axle Hole',
                    'color_id'=>'80',
                    'number'=>'6035029',
                    'bricklink_number'=>'4032',
                    'other_numbers'=>'4032b',
                    'price'=>'12',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.37',
                    'amount'=>3
                ],
                [
                    'title'=>'Plate 1 x 2',
                    'color_id'=>'80',
                    'number'=>'6013102',
                    'bricklink_number'=>'3023',
                    'other_numbers'=>'6225, 28653',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.36',
                    'amount'=>2
                ],
                [
                    'title'=>'Minifigure, Utensil Ski Pole 3L with Handle, Stop Ring and Side Stops',
                    'color_id'=>'80',
                    'number'=>'6233298',
                    'bricklink_number'=>'90540',
                    'other_numbers'=>'18745',
                    'price'=>'15',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.11',
                    'amount'=>1
                ],
                #trans-orange
                [
                    'title'=>'Wave Rounded Straight Single with Small Pin End (Candle Flame)',
                    'color_id'=>'98',
                    'number'=>'6236437',
                    'bricklink_number'=>'37775',
                    'other_numbers'=>'',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.1',
                    'amount'=>3
                ],
                #reddish brown
                [
                    'title'=>'Plate, Round 1 x 1',
                    'color_id'=>'88',
                    'number'=>'4216581',
                    'bricklink_number'=>'4073',
                    'other_numbers'=>'6141, 15570, 30057, 34823, 39799, 44325, 51809',
                    'price'=>'3',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.12',
                    'amount'=>3
                ],
                [
                    'title'=>'Plate, Round 1 x 1 with Open Stud',
                    'color_id'=>'88',
                    'number'=>'6215659',
                    'bricklink_number'=>'85861',
                    'other_numbers'=>'28626, 29387',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.1',
                    'amount'=>4
                ],
                [
                    'title'=>'Brick, Modified 1 x 1 with Headlight',
                    'color_id'=>'88',
                    'number'=>'4225469',
                    'bricklink_number'=>'4070',
                    'other_numbers'=>'4070a, 30069, 35388',
                    'price'=>'8.5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.36',
                    'amount'=>3
                ],
                [
                    'title'=>'Minifigure, Utensil Wand, 2 on Sprue',
                    'color_id'=>'88',
                    'number'=>'6232210',
                    'bricklink_number'=>'36752',
                    'other_numbers'=>'',
                    'price'=>'30',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.24',
                    'amount'=>1
                ],
                [
                    'title'=>'Technic, Axle and Pin Connector Angled #3 - 157.5 degrees',
                    'color_id'=>'88',
                    'number'=>'4610666',
                    'bricklink_number'=>'32016',
                    'other_numbers'=>'42128',
                    'price'=>'6.5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.67',
                    'amount'=>8
                ],
                [
                    'title'=>'Dish 2 x 2 Inverted (Radar)',
                    'color_id'=>'88',
                    'number'=>'4660435',
                    'bricklink_number'=>'4740',
                    'other_numbers'=>'17964, 22669, 30063, 35395, 64938, 71874',
                    'price'=>'12',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.28',
                    'amount'=>1
                ],
                [
                    'title'=>'Carrot Top / Twig',
                    'color_id'=>'88',
                    'number'=>'6078605',
                    'bricklink_number'=>'33183',
                    'other_numbers'=>'',
                    'price'=>'3',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.16',
                    'amount'=>4
                ],
                [
                    'title'=>'Technic, Brick 1 x 2 with Hole',
                    'color_id'=>'88',
                    'number'=>'4211252',
                    'bricklink_number'=>'3700',
                    'other_numbers'=>'',
                    'price'=>'4',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.82',
                    'amount'=>4
                ],
                [
                    'title'=>'Panel 1 x 2 x 2 with Side Supports - Hollow Studs',
                    'color_id'=>'88',
                    'number'=>'6064188',
                    'bricklink_number'=>'87552',
                    'other_numbers'=>'35378, 94638',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.05',
                    'amount'=>2
                ],
                [
                    'title'=>'Plate 1 x 2',
                    'color_id'=>'88',
                    'number'=>'4211150',
                    'bricklink_number'=>'3023',
                    'other_numbers'=>'6225, 28653',
                    'price'=>'7',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.36',
                    'amount'=>3
                ],
                [
                    'title'=>'Panel 1 x 2 x 1 with Rounded Corners and Center Divider',
                    'color_id'=>'88',
                    'number'=>'6133860',
                    'bricklink_number'=>'93095',
                    'other_numbers'=>'18971',
                    'price'=>'7',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.49',
                    'amount'=>2
                ],
                [
                    'title'=>'Bracket 1 x 2 - 1 x 2 Inverted',
                    'color_id'=>'88',
                    'number'=>'6174856',
                    'bricklink_number'=>'99780',
                    'other_numbers'=>'',
                    'price'=>'8',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.55',
                    'amount'=>3
                ],
                [
                    'title'=>'Cattle Horn, Long',
                    'color_id'=>'88',
                    'number'=>'6133924',
                    'bricklink_number'=>'13564',
                    'other_numbers'=>'',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.14',
                    'amount'=>3
                ],
                [
                    'title'=>'Brick 2 x 2 Corner',
                    'color_id'=>'88',
                    'number'=>'4211200',
                    'bricklink_number'=>'2357',
                    'other_numbers'=>'',
                    'price'=>'7',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.25',
                    'amount'=>3
                ],
                [
                    'title'=>'Minifigure, Utensil Briefcase / Suitcase',
                    'color_id'=>'88',
                    'number'=>'4211235',
                    'bricklink_number'=>'4449',
                    'other_numbers'=>'',
                    'price'=>'20',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.49',
                    'amount'=>2
                ],
                [
                    'title'=>'Slope 33 3 x 2',
                    'color_id'=>'88',
                    'number'=>'4216625',
                    'bricklink_number'=>'3298',
                    'other_numbers'=>'30474',
                    'price'=>'8.5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.33',
                    'amount'=>2
                ],
                [
                    'title'=>'Cylinder Half 2 x 4 x 4',
                    'color_id'=>'88',
                    'number'=>'6234539',
                    'bricklink_number'=>'6259',
                    'other_numbers'=>'6218, 20430, 35280',
                    'price'=>'45',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'3.92',
                    'amount'=>2
                ],
                [
                    'title'=>'Technic, Brick 1 x 4 with Holes',
                    'color_id'=>'88',
                    'number'=>'4267994',
                    'bricklink_number'=>'3701',
                    'other_numbers'=>'',
                    'price'=>'6.4',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.46',
                    'amount'=>2
                ],
                [
                    'title'=>'Plate 1 x 4',
                    'color_id'=>'88',
                    'number'=>'4211190',
                    'bricklink_number'=>'3710',
                    'other_numbers'=>'',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.71',
                    'amount'=>8
                ],
                [
                    'title'=>'Technic, Plate 1 x 5 with Smooth Ends, 4 Studs and Center Axle Hole',
                    'color_id'=>'88',
                    'number'=>'6035580',
                    'bricklink_number'=>'32124',
                    'other_numbers'=>'50029',
                    'price'=>'6',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.86',
                    'amount'=>4
                ],
                [
                    'title'=>'Arch 1 x 6 Raised Arch',
                    'color_id'=>'88',
                    'number'=>'4655611',
                    'bricklink_number'=>'92950',
                    'other_numbers'=>'',
                    'price'=>'5.2',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.64',
                    'amount'=>2
                ],
                #Light Gray
                [
                    'title'=>'Slope 30 1 x 1 x 2/3',
                    'color_id'=>'86',
                    'number'=>'4521921',
                    'bricklink_number'=>'54200',
                    'other_numbers'=>'18862, 33847, 35338, 50746, 63290',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.21 ',
                    'amount'=>3
                ],
                [
                    'title'=>'Tile, Modified 1 x 1 with Open O Clip',
                    'color_id'=>'86',
                    'number'=>'6071229',
                    'bricklink_number'=>'15712',
                    'other_numbers'=>'44842',
                    'price'=>'4',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.2',
                    'amount'=>2
                ],
                [
                    'title'=>'Technic, Axle 1L with Tow Ball',
                    'color_id'=>'86',
                    'number'=>'4211375',
                    'bricklink_number'=>'2736',
                    'other_numbers'=>'3985',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.27',
                    'amount'=>4
                ],
                [
                    'title'=>'Tile, Round 2 x 2 with Open Stud',
                    'color_id'=>'86',
                    'number'=>'6183782',
                    'bricklink_number'=>'18674',
                    'other_numbers'=>'',
                    'price'=>'19',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.35',
                    'amount'=>1
                ],
                [
                    'title'=>'Plate, Modified 1 x 2 with Small Tow Ball Socket on Side',
                    'color_id'=>'86',
                    'number'=>'6043656',
                    'bricklink_number'=>'14704',
                    'other_numbers'=>'',
                    'price'=>'7',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.55',
                    'amount'=>4
                ],
                [
                    'title'=>'Plate, Modified 1 x 2 with Clip on Side (Horizontal Grip)',
                    'color_id'=>'86',
                    'number'=>'6028812',
                    'bricklink_number'=>'11476',
                    'other_numbers'=>'65458',
                    'price'=>'9',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.46',
                    'amount'=>1
                ],
                [
                    'title'=>'Tile, Modified 1 x 2 Grille with Bottom Groove / Lip',
                    'color_id'=>'86',
                    'number'=>'4211350',
                    'bricklink_number'=>'2412b',
                    'other_numbers'=>'15561, 30244, 35248, 51815, 71957, 72582, 78812',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.23',
                    'amount'=>1
                ],
                [
                    'title'=>'Wedge, Plate 2 x 2 Cut Corner',
                    'color_id'=>'86',
                    'number'=>'6186657',
                    'bricklink_number'=>'26601',
                    'other_numbers'=>'',
                    'price'=>'15',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.5',
                    'amount'=>1
                ],
                [
                    'title'=>'Panel 1 x 2 x 1 with Rounded Corners',
                    'color_id'=>'86',
                    'number'=>'6146223',
                    'bricklink_number'=>'4865b',
                    'other_numbers'=>'15714, 26169, 35293',
                    'price'=>'9',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.46',
                    'amount'=>2
                ],
                [
                    'title'=>'Plate, Modified 1 x 2 with Bar Arm Up (Horizontal Arm 5mm)',
                    'color_id'=>'86',
                    'number'=>'4611702',
                    'bricklink_number'=>'4623b',
                    'other_numbers'=>'43876, 88072',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0',
                    'amount'=>2
                ],
                [
                    'title'=>'Bracket 1 x 2 - 1 x 2',
                    'color_id'=>'86',
                    'number'=>'4654582',
                    'bricklink_number'=>'99781',
                    'other_numbers'=>'',
                    'price'=>'11',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.55',
                    'amount'=>1
                ],
                [
                    'title'=>'Plate 1 x 3',
                    'color_id'=>'86',
                    'number'=>'4211429',
                    'bricklink_number'=>'3623',
                    'other_numbers'=>'',
                    'price'=>'12',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.53',
                    'amount'=>4
                ],
                [
                    'title'=>'Plate 2 x 4',
                    'color_id'=>'86',
                    'number'=>'4211395',
                    'bricklink_number'=>'3020',
                    'other_numbers'=>'',
                    'price'=>'11',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.2',
                    'amount'=>4
                ],
                [
                    'title'=>'Vehicle, Mudguard 1 1/2 x 6 x 1 with Arch',
                    'color_id'=>'86',
                    'number'=>'4532589',
                    'bricklink_number'=>'62361',
                    'other_numbers'=>'4925, 63970',
                    'price'=>'22.5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.23',
                    'amount'=>1
                ],
                #Dark Bluish Gray
                [
                    'title'=>'Minifigure, Weapon Spear Tip with Fins',
                    'color_id'=>'85',
                    'number'=>'6230282',
                    'bricklink_number'=>'24482',
                    'other_numbers'=>'',
                    'price'=>'20',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.15',
                    'amount'=>1
                ],
                [
                    'title'=>'Cone 1 x 1',
                    'color_id'=>'85',
                    'number'=>'4529240',
                    'bricklink_number'=>'4589',
                    'other_numbers'=>'6188, 55525',
                    'price'=>'6',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.26',
                    'amount'=>3
                ],
                [
                    'title'=>'Wheel Center Small with Stub Axles (Pulley Wheel)',
                    'color_id'=>'85',
                    'number'=>'6005463',
                    'bricklink_number'=>'3464',
                    'other_numbers'=>'',
                    'price'=>'7.2',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.25',
                    'amount'=>1
                ],
                [
                    'title'=>'Bracket 1 x 1 - 1 x 1 Inverted',
                    'color_id'=>'85',
                    'number'=>'6225494',
                    'bricklink_number'=>'36840 ',
                    'other_numbers'=>'',
                    'price'=>'11',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.29',
                    'amount'=>2
                ],
                [
                    'title'=>'Bracket 1 x 2 - 1 x 2 Inverted',
                    'color_id'=>'85',
                    'number'=>'6000606',
                    'bricklink_number'=>'99780',
                    'other_numbers'=>'',
                    'price'=>'7',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.55',
                    'amount'=>1
                ],
                [
                    'title'=>'Plate 2 x 3',
                    'color_id'=>'85',
                    'number'=>'4211043',
                    'bricklink_number'=>'3021',
                    'other_numbers'=>'03021',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.93',
                    'amount'=>2
                ],
                [
                    'title'=>'Technic, Plate 2 x 4 with 3 Holes',
                    'color_id'=>'85',
                    'number'=>'4227398',
                    'bricklink_number'=>'3709b',
                    'other_numbers'=>'',
                    'price'=>'4',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.15',
                    'amount'=>1
                ],
                [
                    'title'=>'Tower Roof 2 x 4 x 4 Half Cone Shaped with Roof Tiles',
                    'color_id'=>'85',
                    'number'=>'6230280',
                    'bricklink_number'=>'35563',
                    'other_numbers'=>'',
                    'price'=>'38',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'2.56',
                    'amount'=>2
                ],
                [
                    'title'=>'Technic, Axle 5.5L with Stop',
                    'color_id'=>'85',
                    'number'=>'4508553',
                    'bricklink_number'=>'32209',
                    'other_numbers'=>'59426',
                    'price'=>'4',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.83',
                    'amount'=>1
                ],
                [
                    'title'=>'Technic, Axle 8L with Stop',
                    'color_id'=>'85',
                    'number'=>'4499858',
                    'bricklink_number'=>'55013',
                    'other_numbers'=>'',
                    'price'=>'11',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.18',
                    'amount'=>1
                ],
                [
                    'title'=>'Plate, Modified 10 x 10 Octagonal with 6 x 6 Open Center',
                    'color_id'=>'85',
                    'number'=>'6172931',
                    'bricklink_number'=>'6063',
                    'other_numbers'=>'29159',
                    'price'=>'14',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'6.5',
                    'amount'=>1
                ],
                #Pink
                [
                    'title'=>'Plate, Round 1 x 1',
                    'color_id'=>'47',
                    'number'=>'6195315',
                    'bricklink_number'=>'4073',
                    'other_numbers'=>'6141, 15570, 30057, 34823, 39799, 44325, 51809',
                    'price'=>'2',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.12',
                    'amount'=>2
                ],
                #
                [
                    'title'=>'Tile, Round 1 x 1 with Bar and Pin Holder',
                    'color_id'=>'115',
                    'number'=>'6186672',
                    'bricklink_number'=>'20482',
                    'other_numbers'=>'31561, 31570, 100765',
                    'price'=>'6',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.16',
                    'amount'=>1
                ],
                [
                    'title'=>'Cone 1 1/6 x 1 1/6 x 2/3 (Fez)',
                    'color_id'=>'115',
                    'number'=>'6173139',
                    'bricklink_number'=>'85975',
                    'other_numbers'=>'29175',
                    'price'=>'11',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.29',
                    'amount'=>1
                ],
                [
                    'title'=>'Minifigure, Utensil Telescope',
                    'color_id'=>'115',
                    'number'=>'4538126',
                    'bricklink_number'=>'64644',
                    'other_numbers'=>'',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.22',
                    'amount'=>1
                ],
                #Dark Brown
                [
                    'title'=>'Brick, Round 1 x 1',
                    'color_id'=>'120',
                    'number'=>'6022105',
                    'bricklink_number'=>'3062',
                    'other_numbers'=>'3062b, 18860, 30068, 35390',
                    'price'=>'14',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.28',
                    'amount'=>1
                ],
                [
                    'title'=>'Minifigure, Utensil Wand, 2 on Sprue',
                    'color_id'=>'120',
                    'number'=>'6235076',
                    'bricklink_number'=>'36752',
                    'other_numbers'=>'',
                    'price'=>'20',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.24',
                    'amount'=>1
                ],
                [
                    'title'=>'Brick, Round 2 x 2 with Axle Hole and Grille / Fluted Profile',
                    'color_id'=>'120',
                    'number'=>'6109329',
                    'bricklink_number'=>'92947',
                    'other_numbers'=>'',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.98',
                    'amount'=>1
                ],
                [
                    'title'=>'Brick, Modified 1 x 2 with Log Profile',
                    'color_id'=>'120',
                    'number'=>'4519970',
                    'bricklink_number'=>'30136',
                    'other_numbers'=>'',
                    'price'=>'7',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.69',
                    'amount'=>4
                ],
                [
                    'title'=>'Slope 45 2 x 1',
                    'color_id'=>'120',
                    'number'=>'4518557',
                    'bricklink_number'=>'3040',
                    'other_numbers'=>'6270, 35281',
                    'price'=>'7',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.69',
                    'amount'=>3
                ],
                [
                    'title'=>'Minifigure, Utensil Telescope',
                    'color_id'=>'120',
                    'number'=>'4538950',
                    'bricklink_number'=>'64644',
                    'other_numbers'=>'',
                    'price'=>'13',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.22',
                    'amount'=>1
                ],
                [
                    'title'=>'Elephant Tail / Trunk with Bar End - Short Curved Tip',
                    'color_id'=>'120',
                    'number'=>'6171006',
                    'bricklink_number'=>'43892',
                    'other_numbers'=>'28959',
                    'price'=>'25',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.93',
                    'amount'=>12
                ],
                [
                    'title'=>'Technic, Axle and Pin Connector Triple',
                    'color_id'=>'120',
                    'number'=>'6005755',
                    'bricklink_number'=>'10288',
                    'other_numbers'=>'49155',
                    'price'=>'15',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.22',
                    'amount'=>4
                ],
                [
                    'title'=>'Bar 3L (Bar Arrow)',
                    'color_id'=>'120',
                    'number'=>'6199910',
                    'bricklink_number'=>'87994',
                    'other_numbers'=>'17715, 19385, 37078',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.2',
                    'amount'=>1
                ],
                [
                    'title'=>'Plate, Round 4 x 4 with Hole',
                    'color_id'=>'120',
                    'number'=>'6005030',
                    'bricklink_number'=>'60474',
                    'other_numbers'=>'',
                    'price'=>'8',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.6',
                    'amount'=>4
                ],
                [
                    'title'=>'Dinosaur Tail / Neck Middle Section with Pin',
                    'color_id'=>'120',
                    'number'=>'6109321',
                    'bricklink_number'=>'40378',
                    'other_numbers'=>'51274',
                    'price'=>'35',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'2.33',
                    'amount'=>4
                ],
                #Trans-Bright green
                [
                    'title'=>'Rock 1 x 1 Crystal 5 Point',
                    'color_id'=>'108',
                    'number'=>'6134621',
                    'bricklink_number'=>'52',
                    'other_numbers'=>'15584, 15585, 28623, 29377, 30385, 61748, 61749, 70770, 71968',
                    'price'=>'25',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.5',
                    'amount'=>1
                ],
                #
                [
                    'title'=>'Minifigure, Utensil Goblet',
                    'color_id'=>'95',
                    'number'=>'6107389',
                    'bricklink_number'=>'2343',
                    'other_numbers'=>'6269, 28657, 30002',
                    'price'=>'1',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.22',
                    'amount'=>3
                ],
                [
                    'title'=>'Wheel 11mm D. x 6mm with Smooth Hubcap',
                    'color_id'=>'95',
                    'number'=>'4624473',
                    'bricklink_number'=>'93594',
                    'other_numbers'=>'',
                    'price'=>'5.1',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.22',
                    'amount'=>4
                ],
                [
                    'title'=>'Plate, Modified 1 x 2 with Door Rail',
                    'color_id'=>'95',
                    'number'=>'6132264',
                    'bricklink_number'=>'32028',
                    'other_numbers'=>'',
                    'price'=>'10',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.44',
                    'amount'=>5
                ],
                #
                [
                    'title'=>'Minifigure, Utensil Lantern',
                    'color_id'=>'77',
                    'number'=>'6234116',
                    'bricklink_number'=>'37776',
                    'other_numbers'=>'',
                    'price'=>'50',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.48',
                    'amount'=>1
                ],
                #Olive Green
                [
                    'title'=>'Slope 30 1 x 1 x 2/3',
                    'color_id'=>'155',
                    'number'=>'6002841',
                    'bricklink_number'=>'54200',
                    'other_numbers'=>'18862, 33847, 35338, 50746, 63290',
                    'price'=>'5',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.22',
                    'amount'=>5
                ],
                [
                    'title'=>'Slope 45 2 x 2 Double Concave',
                    'color_id'=>'155',
                    'number'=>'6193947',
                    'bricklink_number'=>'3046',
                    'other_numbers'=>'3046a, 3046b, 4723',
                    'price'=>'20',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'1.11',
                    'amount'=>4
                ],
                [
                    'title'=>'Tile, Round Corner 2 x 2 Macaroni',
                    'color_id'=>'155',
                    'number'=>'6218089',
                    'bricklink_number'=>'27925',
                    'other_numbers'=>'67124, 78560',
                    'price'=>'9',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.3',
                    'amount'=>4
                ],
                [
                    'title'=>'Plate, Modified 1 x 4 with 2 Studs without Groove',
                    'color_id'=>'155',
                    'number'=>'6024727',
                    'bricklink_number'=>'92593',
                    'other_numbers'=>'',
                    'price'=>'11',
                    'is_available'=>'1',
                    'category_id'=>'1',
                    'weight'=>'0.61',
                    'amount'=>1
                ],

                #sets
                [
                    'title'=>'Snow Groomer',
                    'color_id'=>'1000',
                    'number'=>'42148',
                    'bricklink_number'=>'42148-1',
                    'other_numbers'=>'',
                    'price'=>'800',
                    'is_available'=>'1',
                    'category_id'=>'3',
                    'amount'=>1
                ],
            ];

        foreach ($data as $item)
        {
            Product::create($item);
        }
        dd('succ');
    }
}
